version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d socialnetwork"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:secretpassword@database:5432/socialnetwork
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data: